export const HOME_ROUTE = '/'
export const SERVICES_ROUTE = '/services'
export const CLINIC_ROUTE = '/clinic'
export const DOCTORS_ROUTE = '/doctors'
export const CONTACT_ROUTE = '/contact'
export const LOGIN_ROUTE = '/login'
export const REGISTER_ROUTE = '/register'
